### ISSUE TITLE
Wierd result with mexitek/phpcolors

### ISSUE THREAD

**Issue by zraly** [dg/composer-frontline#6]
I just got this result

 mexitek/phpcolors   ^1.0  →  ^0.5.0 

Any idea why? Thanks.

**Comment by dg** [comment]
I tried it (only mexitek/phpcolors in project) and it didn't happen.

**Comment by zraly** [comment]
Any debug I could do to gather more information what is happening?

**Comment by dg** [comment]
What version of PHP do you have? On command line.

**Comment by zraly** [comment]
~ php -v
PHP 8.0.0 (cli) (built: Nov 26 2020 17:55:32) ( NTS )
Copyright (c) The PHP Group
Zend Engine v4.0.0-dev, Copyright (c) Zend Technologies
    with Zend OPcache v8.0.0, Copyright (c), by Zend Technologies

**Comment by dg** [comment]
When I make an empty project and run this:

```
W:\yyyy>composer require mexitek/phpcolors
Using version ^1.0 for mexitek/phpcolors
./composer.json has been created
Loading composer repositories with package information
Updating dependencies (including require-dev)
Package operations: 1 install, 0 updates, 0 removals
  - Installing mexitek/phpcolors (v1.0.2): Loading from cache
Writing lock file
Generating optimized autoload files

W:\yyyy>composer frontline
All version constraints in composer.json are up to date.

W:\yyyy>php -v

W:\yyyy>C:\PHP\php80\php.exe -c C:\PHP\php80\php-no-xdebug.ini -v
PHP 8.0.0 (cli) (built: Nov 24 2020 22:02:57) ( ZTS Visual C++ 2019 x64 )
```

Sorry, I can't help.

**Comment by zraly** [comment]
I was just able to find, that this returns the wrong version, but it's a thing of composer, so maybe it's something strange there.

https://github.com/dg/composer-frontline/blob/e8e8372202d3d51f6db21bd7273f5723aa399571/src/UpdateCommand.php#L106

Nothing doing, thanks for your time.

**Comment by dg** [comment]
I don't understand how Composer API works at all, I'm a bastlič.
